CREATE DATABASE huellas;

DROP TABLE IF EXISTS rh.tbl_empleados CASCADE;

CREATE SEQUENCE IF NOT EXISTS rh.tbl_empleados_id_empleado_seq
    START 1
    INCREMENT 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE rh.tbl_empleados
(
    id_empleado integer NOT NULL DEFAULT nextval('rh.tbl_empleados_id_empleado_seq'),
    nombre_empleado varchar(100) NOT NULL,
    apellido_paterno_empleado varchar(100) NOT NULL,
    apellido_materno_empleado varchar(100) NOT NULL,
    id_recinto integer,
    id_departamento integer,
    centro_costo varchar(100),
    fecha_nacimiento date,
    rfc varchar(20),
    curp varchar(50),
    domicilio_trabajo varchar(255),
    domicilio_particular varchar(255),
    nss varchar(20),
    num_credito_infonavit varchar(20),
    fecha_ingreso date,
    sd varchar(100),
    sueldo_base numeric(9,2),
    incentivo_productividad numeric(9,2),
    bono_puntualidad numeric(9,2),
    neto_quincenal numeric(9,2),
    vigencia_contrato date,
    email varchar(100),
    id_banco integer,
    clabe_interbancaria varchar(50),
    id_periodo_pago integer,
    linea_corporativa varchar(20),
    activo smallint DEFAULT 1,
    log timestamp DEFAULT now(),
    id_puesto integer,
    codigo varchar(255),
    foto varchar(255) DEFAULT '',
    id_domicilio_laboral integer,
    num_cuenta varchar(20),
    codigo_control varchar(255),
    reporta_ubicacion smallint DEFAULT 0,
    id_semana_laboral integer DEFAULT 1,
    id_empresa integer DEFAULT 1 NOT NULL,
    num_empleado bigint,
    huella_digital bytea,
    huella text,
    id_horario_comida integer DEFAULT 1,
    id_contpaq_fiscal integer,
    id_contpaq_no_fiscal integer,
    region varchar(20),
    sueldo_diario_fiscal double precision,
    sueldo_diario_no_fiscal double precision,
    horas_extra smallint DEFAULT 0,
    status_angel integer DEFAULT 0,
    id_parent integer,
    token_firebase text,
    api_key_firebase text,
    plataforma varchar(20),
    id_encargado integer,
    autoriza smallint DEFAULT 0,
    fecha_baja date,
    password_app varchar(255),
    id_usuario integer,
    es_director_gral smallint DEFAULT 0,
    lugar_nacimiento varchar(100),
    cp varchar(10),
    id_estado_civil integer,
    num_hijos integer,
    descripcion text,
    email_corporativo varchar(50),
    telefono varchar(20),
    celular varchar(20),
    tipo_sangre varchar(10),
    alergias text,
    contacto_emergencia varchar(255),
    telefono_emergencia varchar(20),
    id_nacionalidad integer,
    id_area integer,
    id_centro_trabajo integer,
    estatus varchar(10) DEFAULT 'ACTIVO',
    fecha_reingreso date,
    id_tipo_baja integer,
    motivo_baja text,
    finiquito double precision,
    indemnizacion double precision,
    recontratable smallint DEFAULT 1,
    online smallint DEFAULT 0,
    last_login timestamp,
    activa_email_corporativo smallint DEFAULT 0,
    home_office smallint DEFAULT 0,
    id_usuario_add integer,
    autoriza_edicion_domicilio integer DEFAULT 0,
    latitude_empleado numeric(10,8),
    longitude_empleado numeric(11,8),
    domicilio_laboral_actual text,
    fecha_actualizacion_ubicacion timestamp,
    huella_actual smallint DEFAULT 0,
    check_app smallint DEFAULT 1,

    PRIMARY KEY (id_empleado)
);

ALTER TABLE rh.tbl_empleados
ADD COLUMN huella_gzip text NULL;
