-- Crear esquema RH si no existe
CREATE SCHEMA IF NOT EXISTS rh;

-- Crear tabla tbl_empleados
CREATE TABLE IF NOT EXISTS rh.tbl_empleados (
    id_empleado SERIAL PRIMARY KEY,
    nombre_empleado VARCHAR(100) NOT NULL,
    apellido_paterno_empleado VARCHAR(100) NOT NULL,
    apellido_materno_empleado VARCHAR(100) NOT NULL,
    id_recinto INTEGER,
    id_departamento INTEGER,
    centro_costo VARCHAR(100),
    fecha_nacimiento DATE,
    rfc VARCHAR(20),
    curp VARCHAR(50),
    domicilio_trabajo VARCHAR(255),
    domicilio_particular VARCHAR(255),
    nss VARCHAR(20),
    num_credito_infonavit VARCHAR(20),
    fecha_ingreso DATE,
    sd VARCHAR(100),
    sueldo_base NUMERIC(9,2),
    incentivo_productividad NUMERIC(9,2),
    bono_puntualidad NUMERIC(9,2),
    neto_quincenal NUMERIC(9,2),
    vigencia_contrato DATE,
    email VARCHAR(100),
    id_banco INTEGER,
    clabe_interbancaria VARCHAR(50),
    id_periodo_pago INTEGER,
    linea_corporativa VARCHAR(20),
    activo SMALLINT DEFAULT 1,
    log TIMESTAMP DEFAULT NOW(),
    id_puesto INTEGER,
    codigo VARCHAR(255),
    foto VARCHAR(255) DEFAULT '',
    id_domicilio_laboral INTEGER,
    num_cuenta VARCHAR(20),
    codigo_control VARCHAR(255),
    reporta_ubicacion SMALLINT DEFAULT 0,
    id_semana_laboral INTEGER DEFAULT 1,
    id_empresa INTEGER DEFAULT 1 NOT NULL,
    num_empleado BIGINT,
    huella_digital BYTEA,
    huella TEXT,
    id_horario_comida INTEGER DEFAULT 1,
    id_contpaq_fiscal INTEGER,
    id_contpaq_no_fiscal INTEGER,
    region VARCHAR(20),
    sueldo_diario_fiscal DOUBLE PRECISION,
    sueldo_diario_no_fiscal DOUBLE PRECISION,
    horas_extra SMALLINT DEFAULT 0,
    status_angel INTEGER DEFAULT 0,
    id_parent INTEGER,
    token_firebase TEXT,
    api_key_firebase TEXT,
    plataforma VARCHAR(20),
    id_encargado INTEGER,
    autoriza SMALLINT DEFAULT 0,
    fecha_baja DATE,
    password_app VARCHAR(255),
    id_usuario INTEGER,
    es_director_gral SMALLINT DEFAULT 0,
    lugar_nacimiento VARCHAR(100),
    cp VARCHAR(10),
    id_estado_civil INTEGER,
    num_hijos INTEGER,
    descripcion TEXT,
    email_corporativo VARCHAR(50),
    telefono VARCHAR(20),
    celular VARCHAR(20),
    tipo_sangre VARCHAR(10),
    alergias TEXT,
    contacto_emergencia VARCHAR(255),
    telefono_emergencia VARCHAR(20),
    id_nacionalidad INTEGER,
    id_area INTEGER,
    id_centro_trabajo INTEGER,
    estatus VARCHAR(10) DEFAULT 'ACTIVO',
    fecha_reingreso DATE,
    id_tipo_baja INTEGER,
    motivo_baja TEXT,
    finiquito DOUBLE PRECISION,
    indemnizacion DOUBLE PRECISION,
    recontratable SMALLINT DEFAULT 1,
    online SMALLINT DEFAULT 0,
    last_login TIMESTAMP,
    activa_email_corporativo SMALLINT DEFAULT 0,
    home_office SMALLINT DEFAULT 0,
    id_usuario_add INTEGER,
    autoriza_edicion_domicilio INTEGER DEFAULT 0,
    latitude_empleado NUMERIC(10,8),
    longitude_empleado NUMERIC(11,8),
    domicilio_laboral_actual TEXT,
    fecha_actualizacion_ubicacion TIMESTAMP,
    huella_actual SMALLINT DEFAULT 0,
    check_app SMALLINT DEFAULT 1,
    huella_gzip TEXT NULL,
    puesto VARCHAR(255)
);

-- Crear tabla tbl_asistencias
CREATE TABLE IF NOT EXISTS rh.tbl_asistencias (
    id_asistencia SERIAL PRIMARY KEY,
    id_empleado INTEGER NOT NULL REFERENCES rh.tbl_empleados(id_empleado),
    fecha_registro TIMESTAMP DEFAULT NOW(),
    tipo_registro VARCHAR(50),
    observaciones TEXT,
    latitud NUMERIC(10,8),
    longitud NUMERIC(11,8)
);

-- Crear índices para mejor performance
CREATE INDEX IF NOT EXISTS idx_tbl_asistencias_id_empleado ON rh.tbl_asistencias(id_empleado);
CREATE INDEX IF NOT EXISTS idx_tbl_asistencias_fecha_registro ON rh.tbl_asistencias(fecha_registro);
CREATE INDEX IF NOT EXISTS idx_tbl_empleados_activo ON rh.tbl_empleados(activo);
CREATE INDEX IF NOT EXISTS idx_tbl_empleados_huella_gzip ON rh.tbl_empleados(huella_gzip) WHERE huella_gzip IS NOT NULL;
